services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./data:/tmp/data
    environment:
      OLLAMA_MODELS: "/tmp/data/.ollama/models"
  mysql:
    image: mysql:8.4.4
    platform: linux/amd64
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./data/mysql/:/var/lib/mysql
  quepid:
    image: o19s/quepid:8.0.1
    container_name: quepid
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    links:
#      - mysql
      - ollama
    volumes:
      - ./llm_service.rb:/rails/app/services/llm_service.rb
    environment:
      PORT: "3000"
      RACK_ENV: "production"
      RAILS_ENV: "production"
      FORCE_SSL: "false"
      MAX_THREADS: "2"
      WEB_CONCURRENCY: "2"
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_SERVE_STATIC_FILES: "true"
      TC_URL: ""
      PRIVACY_URL: ""
      COOKIES_URL: ""
      QUEPID_GA: ""
      QUEPID_DOMAIN: "https://example.com"
      EMAIL_MARKETING_MODE: "false"
      QUEPID_DEFAULT_SCORER: "AP@10"
      SIGNUP_ENABLED: "true"
      COMMUNAL_SCORERS_ONLY: "false"
      EMAIL_PROVIDER: ""
      EMAIL_SENDER: ""
      QUERY_LIST_SORTABLE: "true"
      QUEPID_PROPHET_ANALYTICS: "true"
      DATABASE_URL: "mysql2://root:password@mysql:3306/db"
      SECRET_KEY_BASE: "<secret key base>"
      LLM_SERVICE_URL: "http://ollama:11434"
      LLM_KEY: "llama2"
      LLM_MODEL: "llama2"
      LLM_TIMEOUT: 600
